### ISSUE TITLE
Typos and inconsistencies in the names of event types and arguments

### ISSUE THREAD

**Issue by fkdosilovic** [tongmeihan1995/DocEE#1]
First of all, thank you for the great dataset. I was able to load and process the dataset quite easily. It was also no problem to reproduce some of the event classification and argument extraction results. I did find some typos and inconsistencies though.

On further inspection of the dataset, I found some typos and inconsistencies in the names of event types and arguments.
Here is a dictionary of possible corrections. Each event type has a dictionary of potential corrections. The key represents the current name of an argument, while the value contains the potential correction. Note that the names of the events are fixed in this dictionary.

```python
ARGUMENTS_CORRECTED = {
    "Air crash": {"crew": "Crew"},
    "Armed Conflict": {
        "Weapon and Equippment used": "Weapon and Equipment used"
    },
    "Disease Outbreaks": {
        "Confirmed/infected cases": "Confirmed/Infected cases"
    },
    "Famine": {"Casualities and Losses": "Casualties and Losses"},
    "Famous Person - Death": {"Data": "Date"},
    "Financial Crisis": {"policy proposals": "Policy proposals"},
    "Gas explosion": {"survivors": "Survivors"},
    "Government Job change - Resignation_Dismissal": {
        "Person resignated": "Resignee"
    },
    "Join in an Organization": {"Annoncement Date": "Announcement Date"},
    "Military Exercise": {"location": "Location"},
    "Organization Established": {"Spokenmen": "Spokesperson"},
    "Regime Change": {"head of government": "Head of government"},
    "Riot": {"Weopon used": "Weapon used"},
    "Tear Up Agreement": {
        "the agency who broke the agreement": "The agency who broke the agreement"
    },
    "Withdraw from an Organization": {"Annoncement Date": "Announcement Date"},
}
```

**Are you aware of the aforementioned typos and mistakes, and do you plan to correct them in the official dataset dump?**

<details>

<summary>List of the corrected event types</summary>

```python
EVENTS_CORRECTED = [
    "Air crash",
    "Armed Conflict",
    "Awards ceremony",
    "Bank Robbery",
    "Break historical records",
    "Diplomatic Talks _ Diplomatic_Negotiation_ Summit Meeting",
    "Diplomatic Visit",
    "Disease Outbreaks",
    "Droughts",
    "Earthquakes",
    "Environment Pollution",
    "Famine",
    "Famous Person - Commit Crime - Accuse",
    "Famous Person - Commit Crime - Arrest",
    "Famous Person - Commit Crime - Investigate",
    "Famous Person - Commit Crime - Release",
    "Famous Person - Commit Crime - Sentence",
    "Famous Person - Death",
    "Famous Person - Divorce",
    "Famous Person - Give a speech",
    "Famous Person - Marriage",
    "Famous Person - Recovered",
    "Famous Person - Sick",
    "Financial Aid",
    "Financial Crisis",
    "Fire",
    "Floods",
    "Gas explosion",
    "Government Job change - Appoint_Inauguration",
    "Government Job change - Election",
    "Government Job change - Resignation_Dismissal",
    "Government Policy Changes",
    "Hurricanes_Tornado_Storm_Blizzard",
    "Insect Disaster",
    "Join in an Organization",
    "Mass Poisoning",
    "Military Exercise",
    "Mine Collapses",
    "Mudslides",
    "New achievements in aerospace",
    "New archeological discoveries",
    "New wonders in nature",
    "Organization Closed",
    "Organization Established",
    "Organization Fine",
    "Organization Merge",
    "Protest_Online Condemnation",
    "Regime Change",
    "Riot",
    "Road Crash",
    "Shipwreck",
    "Sign Agreement",
    "Sports Competition",
    "Strike",
    "Tear Up Agreement",
    "Train collisions",
    "Tsunamis",
    "Volcano Eruption",
    "Withdraw from an Organization",
]
```
</details>

Here is a list of arguments (per event) and the note hinting at the problem. Notes are indicated by `# Note:` prefix.

<details>
<summary>Arguments per event</summary>

### Air crash

Agency to which the aircraft belongs
Alternate Landing Place
Casualties and Losses
Causes
Date
Flight No.
Initially Scheduled Landing Place
Investigator of the accident
Location
Passengers
Service years
Survivors
Taking-off Place
crew    # Note: Mostly a cosmetic change, but still good for consistency.

### Armed Conflict

Attacker
Casualties and Losses
Date
Destruction of installations
End time
Lasting time
Location
Military Strength(Units involved)
Target
Weapon and Equippment used # Note: Typo.

### Awards ceremony

Award
Award field
Date
Employed institution
Host
Location
Reason for winning
Winner

### Bank Robbery

Amount recovered
Arrested
Bank Name
Date
Hostage
Investigating Spokesperson
Investigating agency
Location
Perpetrators
Stolen amount
Transportation
Weapon Used

### Break historical records

Date
Grades
Last time the record was broken
Location
Previous record holder
Record-breaker
Record-breaking project
The Grades of the previous record holder

### Diplomatic Talks _ Diplomatic_Negotiation_ Summit Meeting

Achievement
Date
Location
Participants
Summit Name
Topics of the meeting

### Diplomatic Visit

Country visited
Date
Host
People visiting

### Disease Outbreaks

Areas affected
Causes
Complications
Confirmed/Infected cases
Confirmed/infected cases # Note: Semantically the same as Confirmed/Infected cases.
Cured Rate
Cured cases
Date
Death Rate
Death cases
Disease Name
Epidemic data issuing agency
Location of the outbreak
Number of people hospitalized
Number of people vaccinated and coverage rate
Precautionary measure
Special medicine
Susceptible population
Suspected cases
Symptoms
Vaccine Research and Development Organization
Way for Spreading

### Droughts

Areas Affected
Causes
Damaged Crops & Livestock
Date
Economic Loss
Influenced People
Number of production cuts
Related rivers or lakes
The Worst-Hit Area

### Earthquakes

Aid agency
Aid supplies/amount
Area Affected
Casualties and Losses
Date
Economic loss
Epicenter
Magnitude
Number of Aftershocks
Number of Destroyed building
Number of Houses Rebuilt
Number of People Trapped
Number of evacuated
Number of people rescued
Temporary settlement

### Environment Pollution

Anti-pollution people/organizations
Causes
Date
Location
Number of victims
Party responsible for pollution
Pollution source
Solution

### Famine

Aid agency
Aid supplies/amount
Areas affected
Casualities and Losses # Note: Typo.
Causes
Date
Economic Loss
Number of People Influenced
Response Measures

### Famous Person - Commit Crime - Accuse # Note: Cosmetic change from "CommitCrime" to "Commit Crime".

Defense lawyer
Evidence
Prosecution lawyer
Prosecutor
The Charged Crime
The accused people
Time of the case
Witness

### Famous Person - Commit Crime - Arrest # Note: Cosmetic change from "CommitCrime" to "Commit Crime".

Criminal evidence
Date
Investigating police
Location
Suspect
The Charged Crime

### Famous Person - Commit Crime - Investigate # Note: Cosmetic change from "CommitCrime" to "Commit Crime".

Head of Investigation Team
Investigation agency
Person under investigation
The Whistleblower
The reason for the investigation
Time to investigate
Time to report the issue

### Famous Person - Commit Crime - Release # Note: Cosmetic change from "CommitCrime" to "Commit Crime".

Charges of imprisonment
Defense lawyer
Jail time
Judge
People Released
Place of sentence
Prison Term
Reason for release
Release Time

### Famous Person - Commit Crime - Sentence # Note: Cosmetic change from "CommitCrime" to "Commit Crime".

Accusation
Court
Court time
Defense lawyer
Judge
Judgement Result/Prison Term
Place of sentence
Prosecution lawyer
Release time
Suspect
The sentence claimed by the defense lawyer
The sentence claimed by the prosecutor's lawyer
Time to start sentence
Victim

### Famous Person - Death

Age
Causes
Data # Note: Semantically the same as Date.
Date
Doctor
Location/Hospital
People
Perpetrator
Profession
State before death

### Famous Person - Divorce

Announce platform
Causes
Child
Child Custody
Date
Duration of marriage
Husband
Property division
Wife

### Famous Person - Give a speech

Date
Location
News release agency
Speaker
Speaker status
Ways to watch the speech

### Famous Person - Marriage

Cost
Date
Dress designer
How many times get married
Husband
Invited person
Location
Wedding venue
Wife
Witness

### Famous Person - Recovered

Cost
Date
Doctor and Medical team
Location/Hospital
People
Sequelae
Treatment Method
Type of illness

### Famous Person - Sick

Causes
Date
Doctor and Medical team
Location/Hospital
People
Perpetrator
Symptom

### Financial Aid

Beneficiary
Causes
Date
Funding
Location
Sponsor

### Financial Crisis

Affected Area
Affected industries
Business failures
Causes
Economic Loss
Economists who predicted the crisis
End time
Start time
Unemployed Rate
policy proposals # Note: Cosmetic change.

### Fire

Aid agency
Aid supplies/amount
Casualties and Losses
Causes
Date
Economic loss
Location
Magnitude
Number of Destroyed building
Number of people rescued
Temporary settlement

### Floods

Aid agency
Aid supplies/amount
Areas affected
Casualties and Losses
Causes
Date
Disaster-stricken farmland
Economic Loss
Maximum rainfall in the Affected Area
Missings
Number of damaged houses
Number of evacuated
Number of people rescued
Related rivers or lakes
Temporary settlement
Water level

### Gas explosion

Casualties and Losses
Causes
Compensation
Date
Economic loss
Investigation results of the accident
Investigator of the accident
Location
Number of people evacuated
Responsibility determination
Temporary Security Zone
The hospital where the wounded was taken
survivors

### Government Job change - Appoint_Inauguration

Appointer
Appointment time
Employment agency
Employment position
Inauguration time
Person appointed
Predecessor
Term of office
The age of the person appointed
The last job of the appointed person

### Government Job change - Election

Candidate scandal(Allegations of fraud, etc.)
Candidates and their parties
Date
Election Name
Election Reason/Goal
Electoral System
Location
People casting tie-breaking votes
The Final Seats Result
The Final Vote Number and Percentage
Turnout(who win who lost)
Voting method

### Government Job change - Resignation_Dismissal

Approver
Date
Employment Agency
Person resignated # Note: Changed to "Resignee".
Position
Reason for resignation
Successor
Term of office
The age of the person appointed

### Government Policy Changes

Announcement date
Bill drafting agency
Causes
Deliberating agency
Effective date
Invalid date
Location
Policy Content
Policy Name & Abbreviation

### Hurricanes_Tornado_Storm_Blizzard

Amount of Precipitation
Influence people
Maximum wind speed
People/Organization who predicted the disaster
Storm Formation Location
Storm Formation Time
Storm Hit Location
Storm Hit Time
Storm Name
Storm center location
Storm movement speed
The direction of the storm
Tsunami Warning Level

### Insect Disaster

Aid agency
Aid supplies/amount
Areas affected
Causes
Date
Economic Loss
Influenced Crops and Livelihood
Pests
Response Measures

### Join in an Orgnization # Note: Typo.

Annoncement Date # Note: Typo.
Causes
Countries join the organization
Declarer
Effective Date
Join Conditions
Organization Name
Organization spokesperson
Other members of the organization

### Mass Poisoning

Casualties and Losses
Causes
Compensation
Date
Economic loss
Investigator of the accident
Location
Number of people evacuated
Responsibility determination
Spokeswoman/Spokesman
The hospital where the wounded was taken
Type of the poisoning

### Military Excercise # Note: Typo.

Army Participated
Commanders and their position
Countries participating in the military exercise
Date
Military Exercise Items
Number of people participating in the military exercise
The name of the military exercise
The purpose of the military exercise
Weapons used in military exercises
location # Note: Cosmetic change.

### Mine Collapses

Casualties and Losses
Causes
Compensation
Date
Economic loss
Investigator of the accident
Location
Number for trapped people
Number of days trapped
Rescue start time
Survivors
The hospital where the wounded was taken
Trapped depth

### Mudslides

Aid agency
Aid supplies/amount
Areas affected
Casualties and Losses
Causes
Date
Economic Loss
Influence People
Missings
Number of Destroyed building
Number of evacuated
Number of people rescued
Temporary settlement

### New achievements in aerospace

Carrier rocket
Cooperative agency
Launch Date
Launch Result
Launch Site
Launch country
Mission duration
Participating astronauts
Research & Development department Country
Spacecraft Mission
Spacecraft name
Spokeswoman/Spokesman

### New archeological discoveries

Archaeologist
Discover Location
Discover Time
Historical sites discovered
Reasons for the formation of the Historical sites
Relics discovered and their dates
The organization of the discoverer

### New wonders in nature

Best why to shoot
Causes
Forecasting agency
Lasting Time
Live broadcast platform
The location where the spectacle can be observed
The time when the spectacle appeared
The time when the spectacle disappeared
Types of wonders

### Organization Closed

Causes
Date
Head of Institution
Location
Organization name

### Organization Established

Causes
Date
Head of Institution
Location
Organization name
Registered capital
Spokenmen # Note: Changed to "Spokesperson".

### Organization Fine

Causes
Date
Fined agency
Lawyer
Location
Penalty amount
Regulatory Authority

### Organization Merge

Acquiree
Acquirer
Acquisition amount
Date
Merger terms
The industry in which the organization operates
The leader of the merged organization

### Protest_Online Condemnation

Arrested
Casualties and Losses
Date
Government Reaction
Location
Method
Property damage
Protest Slogan
Protesters
Reason for protest

### Regime Change

Army
Commanders of the army
Country
Date
Provisional government
Time for dignitaries to resign
head of government # Note: Cosmetic change.

### Riot

Belligerents
Casualties and Losses
Causes
Date
Economic Loss
Location
Weopon used # Note: Typo.

### Road Crash

Casualties and Losses
Causes
Compensation
Date
Economic loss
Investigating police
Location
Number of vehicles involved in the crash
Survivors
The hospital where the wounded was taken

### Shipwreck

Agency to which the ship belongs
Casualties and Losses
Causes
Date
Investigator of the accident
Location
Location of wreckage found
Missings
Rescue Organizer
Rescue start time
Rescue tool or method
Ship No.
Survivors
The state of the hull at the time of discovery
Time the crew lost contact
Time to find the wreck

### Sign Agreement

Agreement Content
Agreement Name
Agreement validity period
Contracting parties
Date
Location

### Sports Competition

Champions
Competition items
Contest participant
End time
Game Name
Host country
Lasting time
Location
MVP
Postpone time
Reason for postponement
Score
Start time

### Strike

Boycotted institutions
Duration
Economy Loss
End time
Outcome of the strike
Reason for Strike
Start time
Strike Agencies
Strike Industry
Strikers
Strikers Status

### Tear Up Agreement

Agreement Name
Causes
Date
Other members of the agreement
the agency who broke the agreement

### Train collisions

Agency to which the train belongs
Casualties and Losses
Causes
Date
Economic loss
Investigator of the accident
Location
Missings
Survivors
The hospital where the wounded was taken
Train No.

### Tsunamis

Aid agency
Aid supplies/amount
Area Affected
Casualties and Losses
Causes
Date
Economic loss
Magnitude(Tsunami heights)
Number of Destroyed building
Number of people rescued
People/Organization who predicted the disaster
Tsunami Warning Level
Tsunamis name
Warning Device

### Volcano Eruption

Areas affected
Casualties and Losses
Causes
Economic Loss
Fire Warning Level
Last Outbreak Time
Number of Damaged House
Number of evacuated
Outbreak Date
People/Organization who predicted the disaster
Refuge
The State of the Volcano (dormant or active)
Volcano Name

### Withdraw from an Orgnization # Note: Typo.

Annoncement Date # Note: Typo.
Causes
Countries withdraw the organization
Declarer
Effective Date
Exit Conditions
Organization Name
Organization spokesperson
Other members of the organization

</details>

**Comment by tongmeihan1995** [comment]
Thanks for your kind reminder, we have reformulated the dataset to ensure the consistency of the event argument roles.
