### ISSUE TITLE
Question about entity's repeated mentions

### ISSUE THREAD

**Issue by starsea2044** [tongmeihan1995/DocEE#4]
First of all, thanks for your dataset! I have some questions when using the dataset. In your paper, you say "For repeated mentions that refer to the same entity, we only label once.". But I found a lot of repeated mentions of entities in the dataset. Such as: 
```{"type": "Deceased", "mention": [{"start": 78, "end": 92, "text": "Lech Kaczynski"}, {"start": 2025, "end": 2039, "text": "Lech Kaczynski"}, {"start": 5367, "end": 5381, "text": "Lech Kaczynski"}]}, {"type": "Location/Hospital", "mention": [{"start": 172, "end": 178, "text": "Russia"}, {"start": 3908, "end": 3914, "text": "Russia"}, {"start": 4654, "end": 4660, "text": "Russia"}]}. ```
Did you take repeated mentions into account when evaluation?

**Comment by tongmeihan1995** [comment]
Thanks for following. We remove repeated mentions when evaluation.&nbsp;&nbsp;



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 27, 2023 15:56 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [tongmeihan1995/DocEE] Question about entity's repeated mentions(Issue #4)




 
First of all, thanks for your dataset! I have some questions when using the dataset. In your paper, you say "For repeated mentions that refer to the same entity, we only label once.". But I found a lot of repeated mentions of entities in the dataset. Such as:
 {"type": "Deceased", "mention": [{"start": 78, "end": 92, "text": "Lech Kaczynski"}, {"start": 2025, "end": 2039, "text": "Lech Kaczynski"}, {"start": 5367, "end": 5381, "text": "Lech Kaczynski"}]}, {"type": "Location/Hospital", "mention": [{"start": 172, "end": 178, "text": "Russia"}, {"start": 3908, "end": 3914, "text": "Russia"}, {"start": 4654, "end": 4660, "text": "Russia"}]}. 
 Did you take repeated mentions into account when evaluation?
